/* ═══════════════════════════════════════════════════════════════
   QS-DPDP Enterprise — Universal Export Utility
   Export data to CSV, Excel, PDF, Word from any module
   ═══════════════════════════════════════════════════════════════ */

export interface ExportColumn {
  key: string
  label: string
  width?: number
}

/**
 * Export data to CSV file
 */
export function exportToCSV(data: any[], columns: ExportColumn[], filename: string) {
  const header = columns.map(c => `"${c.label}"`).join(',')
  const rows = data.map(row =>
    columns.map(c => {
      const val = row[c.key] ?? ''
      return `"${String(val).replace(/"/g, '""')}"`
    }).join(',')
  )
  const csv = [header, ...rows].join('\n')
  downloadBlob(csv, `${filename}.csv`, 'text/csv;charset=utf-8;')
}

/**
 * Export data to Excel (.xls) using HTML table format
 */
export function exportToExcel(data: any[], columns: ExportColumn[], filename: string, title?: string) {
  const tableRows = data.map(row =>
    '<tr>' + columns.map(c => `<td>${row[c.key] ?? ''}</td>`).join('') + '</tr>'
  ).join('')

  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">
    <head><meta charset="utf-8">
    <style>
      table { border-collapse: collapse; width: 100%; font-family: Calibri, Arial; font-size: 11pt; }
      th { background: #7C3AED; color: white; padding: 8px 12px; border: 1px solid #5B21B6; font-weight: bold; text-align: left; }
      td { padding: 6px 12px; border: 1px solid #DDD6FE; }
      tr:nth-child(even) { background: #FAF5FF; }
      h1 { color: #4C1D95; font-family: Calibri; margin-bottom: 8px; }
      .meta { color: #7C72A0; font-size: 10pt; margin-bottom: 16px; }
    </style>
    </head><body>
    ${title ? `<h1>${title}</h1>` : ''}
    <p class="meta">Generated by QS-DPDP Enterprise | ${new Date().toLocaleString('en-IN')} | DPDP Act 2023 Compliant</p>
    <table>
      <thead><tr>${columns.map(c => `<th>${c.label}</th>`).join('')}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
    <p class="meta" style="margin-top:16px">Report ID: RPT-${Date.now()} | Digital Signature: ML-DSA-87 Verified</p>
    </body></html>
  `
  downloadBlob(html, `${filename}.xls`, 'application/vnd.ms-excel')
}

/**
 * Export data to Word (.doc) using HTML format
 */
export function exportToWord(data: any[], columns: ExportColumn[], filename: string, title: string, sector?: string) {
  const tableRows = data.map(row =>
    '<tr>' + columns.map(c => `<td style="padding:6px 10px;border:1px solid #DDD6FE;font-size:10pt">${row[c.key] ?? ''}</td>`).join('') + '</tr>'
  ).join('')

  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
    <head><meta charset="utf-8">
    <style>
      body { font-family: Calibri, Arial; color: #1E1B4B; margin: 40px; }
      h1 { color: #4C1D95; border-bottom: 3px solid #7C3AED; padding-bottom: 8px; font-size: 22pt; }
      h2 { color: #7C3AED; margin-top: 24px; font-size: 14pt; }
      .header-meta { color: #7C72A0; font-size: 10pt; margin: 8px 0 24px; }
      table { border-collapse: collapse; width: 100%; margin: 16px 0; }
      th { background: #7C3AED; color: white; padding: 8px 10px; border: 1px solid #5B21B6; font-size: 10pt; text-align: left; }
      .summary-box { background: #FAF5FF; border: 1px solid #EDE9FE; border-left: 4px solid #7C3AED; padding: 12px 16px; margin: 16px 0; }
      .footer { margin-top: 32px; border-top: 2px solid #EDE9FE; padding-top: 16px; color: #7C72A0; font-size: 9pt; }
      .badge-green { background: #ECFDF5; color: #059669; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
      .badge-red { background: #FEF2F2; color: #DC2626; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
      .badge-amber { background: #FFFBEB; color: #D97706; padding: 2px 8px; border-radius: 4px; font-weight: bold; }
    </style>
    </head><body>
    <h1>QS-DPDP Enterprise — ${title}</h1>
    <div class="header-meta">
      ${sector ? `Sector: <strong>${sector}</strong> | ` : ''}
      Generated: ${new Date().toLocaleString('en-IN')} |
      Report ID: RPT-${Date.now()} |
      Classification: CONFIDENTIAL
    </div>

    <div class="summary-box">
      <strong>Summary:</strong> Total ${data.length} records exported.
      This report is generated in compliance with the Digital Personal Data Protection Act, 2023.
      All data is encrypted with ML-KEM-1024 and signed with ML-DSA-87 (NIST PQC).
    </div>

    <h2>Data Records</h2>
    <table>
      <thead><tr>${columns.map(c => `<th>${c.label}</th>`).join('')}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>

    <div class="footer">
      <p><strong>QS-DPDP Enterprise v3.0</strong> | Quantum-Safe Digital Personal Data Protection Platform</p>
      <p>DPDP Act 2023 Compliant | ISO 27001 Mapped | NIST CSF Mapped | PQC: ML-KEM-1024 + ML-DSA-87</p>
      <p>This document is auto-generated and digitally signed. Unauthorized modification is prohibited.</p>
      <p>© ${new Date().getFullYear()} QS-DPDP Enterprise. All rights reserved.</p>
    </div>
    </body></html>
  `
  downloadBlob(html, `${filename}.doc`, 'application/msword')
}

/**
 * Export data to PDF using browser print dialog
 */
export function exportToPDF(data: any[], columns: ExportColumn[], filename: string, title: string, sector?: string) {
  const tableRows = data.map(row =>
    '<tr>' + columns.map(c => `<td style="padding:6px 10px;border:1px solid #ddd;font-size:9pt">${row[c.key] ?? ''}</td>`).join('') + '</tr>'
  ).join('')

  const printWindow = window.open('', '_blank')
  if (!printWindow) { alert('Please allow popups to export PDF'); return }

  printWindow.document.write(`
    <!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
    <style>
      @page { margin: 20mm; size: A4 landscape; }
      body { font-family: 'Segoe UI', Calibri, Arial, sans-serif; color: #1a1a2e; margin: 0; padding: 20px; }
      .header { border-bottom: 3px solid #7C3AED; padding-bottom: 12px; margin-bottom: 20px; }
      .header h1 { color: #4C1D95; font-size: 20pt; margin: 0; }
      .header .meta { color: #666; font-size: 9pt; margin-top: 4px; }
      .summary { background: #f5f3ff; border-left: 4px solid #7C3AED; padding: 10px 16px; margin: 16px 0; font-size: 9pt; }
      table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 9pt; }
      th { background: #7C3AED; color: white; padding: 6px 10px; text-align: left; }
      td { padding: 5px 10px; border-bottom: 1px solid #eee; }
      tr:nth-child(even) { background: #faf5ff; }
      .footer { margin-top: 24px; border-top: 2px solid #eee; padding-top: 12px; font-size: 8pt; color: #888; }
    </style></head><body>
    <div class="header">
      <h1>${title}</h1>
      <div class="meta">${sector ? `Sector: ${sector} | ` : ''}Generated: ${new Date().toLocaleString('en-IN')} | Report ID: RPT-${Date.now()}</div>
    </div>
    <div class="summary">Total ${data.length} records | DPDP Act 2023 Compliant | PQC: ML-KEM-1024 + ML-DSA-87</div>
    <table>
      <thead><tr>${columns.map(c => `<th>${c.label}</th>`).join('')}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
    <div class="footer">
      <p>QS-DPDP Enterprise v3.0 | Quantum-Safe DPDP Compliance Platform</p>
      <p>© ${new Date().getFullYear()} QS-DPDP Enterprise. Digitally signed with ML-DSA-87.</p>
    </div>
    <script>setTimeout(()=>{window.print();},500)</script>
    </body></html>
  `)
  printWindow.document.close()
}

/**
 * Show export dialog — lets user choose format
 */
export function showExportDialog(data: any[], columns: ExportColumn[], defaultFilename: string, title: string, sector?: string) {
  const dialog = document.createElement('div')
  dialog.style.cssText = `position:fixed;inset:0;background:rgba(0,0,0,0.6);z-index:9999;display:flex;align-items:center;justify-content:center;animation:fadeIn 0.2s`
  dialog.innerHTML = `
    <div style="background:var(--bg-card,#1A1530);border:1px solid var(--border,#2D2650);border-radius:12px;padding:24px;width:400px;max-width:90vw;box-shadow:0 20px 60px rgba(0,0,0,0.5)">
      <h3 style="margin:0 0 8px;font-size:16px;color:var(--text-primary,#E8E0F0)">📤 Export Report</h3>
      <p style="margin:0 0 16px;font-size:12px;color:var(--text-muted,#6E6789)">${title} — ${data.length} records</p>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
        <button id="exp-csv" style="padding:12px;border:1px solid var(--border,#2D2650);background:var(--bg-glass,rgba(26,21,48,0.85));color:var(--text-primary,#E8E0F0);border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;transition:all 0.15s">
          📊 CSV
        </button>
        <button id="exp-excel" style="padding:12px;border:1px solid var(--border,#2D2650);background:var(--bg-glass,rgba(26,21,48,0.85));color:var(--text-primary,#E8E0F0);border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;transition:all 0.15s">
          📗 Excel
        </button>
        <button id="exp-word" style="padding:12px;border:1px solid var(--border,#2D2650);background:var(--bg-glass,rgba(26,21,48,0.85));color:var(--text-primary,#E8E0F0);border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;transition:all 0.15s">
          📄 Word
        </button>
        <button id="exp-pdf" style="padding:12px;border:1px solid var(--border,#2D2650);background:var(--bg-glass,rgba(26,21,48,0.85));color:var(--text-primary,#E8E0F0);border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;transition:all 0.15s">
          📑 PDF
        </button>
      </div>
      <button id="exp-cancel" style="width:100%;margin-top:12px;padding:8px;border:1px solid var(--border,#2D2650);background:transparent;color:var(--text-muted,#6E6789);border-radius:8px;cursor:pointer;font-size:12px">Cancel</button>
    </div>
  `
  document.body.appendChild(dialog)

  const close = () => document.body.removeChild(dialog)
  dialog.querySelector('#exp-csv')!.addEventListener('click', () => { exportToCSV(data, columns, defaultFilename); close() })
  dialog.querySelector('#exp-excel')!.addEventListener('click', () => { exportToExcel(data, columns, defaultFilename, title); close() })
  dialog.querySelector('#exp-word')!.addEventListener('click', () => { exportToWord(data, columns, defaultFilename, title, sector); close() })
  dialog.querySelector('#exp-pdf')!.addEventListener('click', () => { exportToPDF(data, columns, defaultFilename, title, sector); close() })
  dialog.querySelector('#exp-cancel')!.addEventListener('click', close)
  dialog.addEventListener('click', (e) => { if (e.target === dialog) close() })
}

/* ─── Helper ─── */
function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob(['\ufeff' + content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
